### ISSUE TITLE
[Bug]: ctrl-space-workaround does not work

### ISSUE THREAD

**Issue by natebragg** [termux/termux-x11#665]
### Problem description

Some systems don't handle CTRL+space correctly.  On my machine, running `xev` from within `termux-x11 -xstartup "aterm"`, pressing and releasing left CTRL results in the following output:

```
KeyPress event, serial 32, synthetic NO, window 0x600001,
    root 0x511, subw 0x0, time 10088320, (1466,1198), root:(1467,1199),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x600001,
    root 0x511, subw 0x0, time 10089266, (1466,1198), root:(1467,1199),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

Pressing left CTRL followed by pressing the space bar results in the following output:

```
KeyPress event, serial 32, synthetic NO, window 0x600001,
    root 0x511, subw 0x0, time 10091627, (1466,1198), root:(1467,1199),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x600001,
    root 0x511, subw 0x0, time 10092033, (1466,1198), root:(1467,1199),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

These are the same except for the time field.  This same issue is present in normal termux, and is fixed using the `ctrl-space-workaround` setting inside the `.termux/termux.properties` file.

Please include a setting that fixes the same issue.

### What steps will reproduce the bug?

Follow the steps above.

### What is the expected behavior?

CTRL+space is processed properly, and gives the correct keycodes inside `xev`.

**Comment by twaik** [comment]
`.termux/termux.properties` is a properties file of termux-app, not related to termux-x11.
Try to disable `Hardware keyboard scancodes workaround` in preferences.

**Comment by natebragg** [comment]
Disabling that did not work.  And yes, I aware that file has nothing to do with termux-x11, I only meant that the behavior was the same between the two, and that that property was how it was fixed in termux.

**Comment by twaik** [comment]
Try using `Prefer scancodes when possible` and if it does not work re-enable hardware keyboard scancodes workaround.

**Comment by twaik** [comment]
Did it work?

**Comment by twaik** [comment]
@natebragg

**Comment by natebragg** [comment]
None of the 4 combinations of these two options enable CTRL+space.  Although they do change the behavior of the keyboard.  I use the us Dvorak layout, and using those options requires me to `setxkbmap 'us(dvorak)'`.

My device is unique, and apparently vanilla termux does not correctly handle this by default, which is why you must use the previously mentioned config line.  Take a look at their code that handles this option to see how they fix CTRL+space on weird devices.

**Comment by twaik** [comment]
Ok, I need the log with "TERMUX_X11_DEBUG=1" of termux-x11 not getting these events. Use this apk.
[app-universal-debug.zip](https://github.com/user-attachments/files/16094839/app-universal-debug.zip)

**Comment by natebragg** [comment]
Here is the log I collected, with some potentially helpful notes added at the top of the file:

[ctrl+space.log](https://github.com/user-attachments/files/16101044/ctrl%2Bspace.log)

In case it helps, this was pretty much the same behavior when I was trying to figure out this issue in the termux app: termux/termux-app#3896 .

As a separate issue, not sure if the following changes are intentional, but on my hardware the debug version you sent me behaves quite differently than the release I had installed.  I use a Meta Quest 3, and after launching `termux-x11`, 1) it required using the controllers which is bizarre as I almost always work using hand tracking, 2) it blew away all the other apps when it launched, meaning I was unable to multitask, 3) the window was unable to be resized, 4) the cursor did not appear outside of the window making the rest of the system unusable, and 5) the font was like 4pt, which was completely unreadible.  Not sure if these are only issues with the debug build or with the non-debug build, but if you can post an apk of the non-debug build I'll test and file any of these bugs that occur there.

**Comment by twaik** [comment]
Oh, it seems like you entered XR mode. It's code was written by @lvonasek.
[app-universal-debug.zip](https://github.com/user-attachments/files/16118252/app-universal-debug.zip)
Try installing this build, long-tapping Termux:X11 icon in app drawer (or how it is done on Meta Oculus Quest, not sure), and uncheck "XR mode" in "Other" section.

**Comment by lvonasek** [comment]
The "XR mode" option isn't there yet. I will create a small PR adding that option during the week.

**Comment by twaik** [comment]
"XR mode is present in the build I sent in zip file...
But the problem is XRActivity not receiving keyboard (physical, not IME) input correctly.

**Comment by lvonasek** [comment]
Adding 
```
<uses-permission android:name="com.oculus.permission.TRACKED_KEYBOARD"/>
```
might help. I will check it later.

**Comment by natebragg** [comment]
Ah!  Now that I understand that this is a new mode, that makes more sense.  I guess my #2&3 are as intended.  Consider the rest to be early user feedback (particularly #1, and to a lesser degree #5).

**Comment by natebragg** [comment]
@twaik I'm not sure I understand, do you want me to use that new apk for the XR mode, or were you saying you need me to collect new logs for the ctrl+space issue?

**Comment by lvonasek** [comment]
@natebragg collect new logs for the ctrl+space issue with XR mode disabled.

To address the issues with XR mode:
1) Hand tracking won't work in XR as it is designed. But I could disable the controller requirement, so the system could be used with other input devices.
2) That's the system behavior, nothing could be done (except disabling XR).
3) That could be implemented at some point.
4) In XR you can access other apps using a home button.
5) The default resolution is "native" which in XR case is pretty high. I could hardcode some smaller resolution instead of the current one.

@twaik, I will address 1) and 5) in a small PR. Will you push your XR mode option?

**Comment by natebragg** [comment]
Here is my new, annotated log using the new apk above with XR mode disabled:

[ctrl+space.log](https://github.com/user-attachments/files/16131166/ctrl%2Bspace.log)

**Comment by twaik** [comment]
Ok, it seems like `ACTION_UP` event is not sent for `KEYCODE_SPACE` for some reason. In termux-app it is fixed by f1e973f0d2000957a21387a8ee2f65bd08c776fb . @Grimler91 can you please help with fixing this?

**Comment by natebragg** [comment]
FTR, I believe this only works for some keyboards, while it breaks others, which is why termux-app fixes it using a configuration setting.

**Comment by twaik** [comment]
And that is a reason I need consultation of the developer who fixed this in other project.

**Comment by natebragg** [comment]
Another comment about the build you linked above: clicking back from within preferences stays on the preferences, and does not return to the activity with the X logo.  To start over, I have to exit the app and restart it.

**Comment by natebragg** [comment]
@lvonasek I just noticed that even with XR mode disabled it still won't let me enter the app without the controllers.  After it's open there's no problem, but to start it pops open a blocking dialog until I pick up a controller.

**Comment by lvonasek** [comment]
> @lvonasek I just noticed that even with XR mode disabled it still won't let me enter the app without the controllers. After it's open there's no problem, but to start it pops open a blocking dialog until I pick up a controller.

I fixed that in this PR:
https://github.com/termux/termux-x11/pull/671

**Comment by twaik** [comment]
@natebragg can you please check the https://github.com/termux/termux-x11/actions/runs/9840251940 build and confirm it works?
@lvonasek there are pending reviews.

**Comment by natebragg** [comment]
@twaik that did not work, although I was only able to test it in XR mode, since the option to disable it was not present in the preferences.

**Comment by twaik** [comment]
@natebragg can you please try to reproduce it in https://github.com/termux/termux-x11/actions/runs/9926318838 ?

**Comment by twaik** [comment]
And I need a log of "Esc" key to make sure it works fine too.

**Comment by natebragg** [comment]
@twaik I instrumented the below log with the presses and releases.  I did four tests (ctrl press -> release; ctrl press -> space press -> space release -> ctrl release; ctrl press -> space press -> ctrl release -> space release; esc press -> esc release).  The can be found starting at line 363.  There's a clear difference, with space presses registered as ctrl release, which space release is correct.  Escape works fine (and has worked fine from the start, I just didn't report it in the comments above).

[ctrl+space.log](https://github.com/user-attachments/files/16236550/ctrl%2Bspace.log)

**Comment by twaik** [comment]
Unfortunately I can not make termux-x11 interpret events if they come in wrong order or with wrong action (in your case it was received with action other than ACTION_DOWN so it was not considered as key press).
I can consider this to be a firmware or IME related quirk which are hard to be debugged and fixed.
Sorry for inconvenience.

**Comment by natebragg** [comment]
@twaik why can't there be a configuration option like in termux-app, as I originally suggested in the issue??  I can't use termux-x11 without this, and I don't understand why it can be done there but not here.

**Comment by natebragg** [comment]
@twaik I'm sure I'm not the only person with a keyboard that has this issue.  The termux-app folks didn't add this for me, it already existed.

**Comment by twaik** [comment]
> why can't there be a configuration option like in termux-app, as I originally suggested in the issue?

Because termux-x11's key handler works other way. It is not compatible with termux-app's key handler.

**Comment by twaik** [comment]
[app-universal-debug.zip](https://github.com/user-attachments/files/16273800/app-universal-debug.zip)
This artifact creates a bit more detailed key log, you can try to use it to create one more annotated log.

**Comment by natebragg** [comment]
Great, thank you!  I think this demonstrates the situation quite well.  As usual, I have instrumented the log starting at line 350.

As you can see, the "false" CTRL release triggered by the space press still has the metaState with META_CTRL_LEFT_ON set, as does the space press after it.  The "true" CTRL release clears that flag.  This is visible in each of the three ctrl+space combinations I tested.

[ctrl+space.log](https://github.com/user-attachments/files/16274538/ctrl%2Bspace.log)

**Comment by natebragg** [comment]
@twaik Thank you again for being willing to take one last look at this.  Your app is an excellent and very needed, and I'd love to be able to continue using it.

**Comment by twaik** [comment]
[app-universal-debug.zip](https://github.com/user-attachments/files/16277653/app-universal-debug.zip)
Ok, it seems like fake ctrl release event came with FLAG_CANCELLED flag. Let's check if ignoring it will work.

**Comment by twaik** [comment]
@natebragg ?

**Comment by natebragg** [comment]
Sorry for the delay, I live in UTC-4 and was asleep.

The behavior was effectively the same.  Here's the annotated log:

[ctrl+space.log](https://github.com/user-attachments/files/16285072/ctrl%2Bspace.log)

**Comment by twaik** [comment]
It is pretty much weird. Key release event for CTRL came in the same time as key press event for SPACE. Probably that is the reason the space key event had repeatCount=1. Events with non-zero repeatCount are filtered out so probably it was the reason space key was not consumed. Weird.

[app-universal-debug.zip](https://github.com/user-attachments/files/16285529/app-universal-debug.zip)

**Comment by natebragg** [comment]
@twaik Here you go.  Starting at line 424.  I tried something a little different this time, pausing between each press and release (something like press, wait 1s, press, wait 1s, release 1s, release, then a longer wait while nothing is pressed).  Hopefully that doesn't mess with things, and is helpful.

[ctrl+space.log](https://github.com/user-attachments/files/16287373/ctrl%2Bspace.log)

**Comment by twaik** [comment]
Everything seems to be fine. Does ctrl+space work in this build? You did not say it.

**Comment by natebragg** [comment]
@twaik sadly it does not work.

**Comment by twaik** [comment]
Can you please capture logs of both xev and logcat in the same session and annotate them?

**Comment by natebragg** [comment]
Here you go.  I instrumented both logs with the first CTRL press, and the ctrl+space.log noting the beginning and end of the xev.log

To corellate times, the xev logs time in ms, so just rebase it from the first ctrl press.

[ctrl+space.log](https://github.com/user-attachments/files/16316651/ctrl%2Bspace.log)
[xev.log](https://github.com/user-attachments/files/16316653/xev.log)

**Comment by twaik** [comment]
And according to both logs everything is fine. I'll show it:

**$\color{red}{KeyPress}$** event, serial 32, synthetic NO, window 0x600001,
&nbsp;&nbsp;&nbsp;&nbsp;root 0x511, subw 0x0, time 4897890, (64,785), root:(65,786),
&nbsp;&nbsp;&nbsp;&nbsp;state 0x0, keycode 37 (keysym 0xffe3, **$\color{red}{Control_L}$**), same_screen YES,
&nbsp;&nbsp;&nbsp;&nbsp;XLookupString gives 0 bytes: 
&nbsp;&nbsp;&nbsp;&nbsp;XmbLookupString gives 0 bytes: 
&nbsp;&nbsp;&nbsp;&nbsp;XFilterEvent returns: False

**$\color{red}{KeyPress}$** event, serial 32, synthetic NO, window 0x600001,
&nbsp;&nbsp;&nbsp;&nbsp;root 0x511, subw 0x0, time 4898741, (64,785), root:(65,786),
&nbsp;&nbsp;&nbsp;&nbsp;state 0x4, keycode 65 (keysym 0x20, **$\color{red}{space}$**), same_screen YES,
&nbsp;&nbsp;&nbsp;&nbsp;XLookupString gives 1 bytes: (00) ""
&nbsp;&nbsp;&nbsp;&nbsp;XmbLookupString gives 1 bytes: (00) ""
&nbsp;&nbsp;&nbsp;&nbsp;XFilterEvent returns: False

**$\color{red}{KeyRelease}$** event, serial 32, synthetic NO, window 0x600001,
&nbsp;&nbsp;&nbsp;&nbsp;root 0x511, subw 0x0, time 4899060, (64,785), root:(65,786),
&nbsp;&nbsp;&nbsp;&nbsp;state 0x4, keycode 65 (keysym 0x20, **$\color{red}{space}$**), same_screen YES,
&nbsp;&nbsp;&nbsp;&nbsp;XLookupString gives 1 bytes: (00) ""
&nbsp;&nbsp;&nbsp;&nbsp;XFilterEvent returns: False

**$\color{red}{KeyRelease}$** event, serial 32, synthetic NO, window 0x600001,
&nbsp;&nbsp;&nbsp;&nbsp;root 0x511, subw 0x0, time 4899465, (64,785), root:(65,786),
&nbsp;&nbsp;&nbsp;&nbsp;state 0x4, keycode 37 (keysym 0xffe3, **$\color{red}{Control_L}$**), same_screen YES,
&nbsp;&nbsp;&nbsp;&nbsp;XLookupString gives 0 bytes: 
&nbsp;&nbsp;&nbsp;&nbsp;XFilterEvent returns: False

So it is being consumed fine. Check your enviironment.

**Comment by natebragg** [comment]
Interesting!  I found out why it was going wrong!  The behavior is quirky.

The log I sent probably displayed the correct behavior because I was going deliberately slow, but when I was just trying it out in my application, I was going more quickly.

If I press CTRL then space within a few ms of each other, the CTRL press shows up instantly, but it actually takes about 400 ms for the space press to show up. If held down, it is then repeated after the normal repeat delay, and then the space release and CTRL release are both instant.

If I press and release space without CTRL pressed, it shows up immediately.

If I press CTRL then space then rapidly press a different key (e.g., K), then the space doesn't register, but K does (with a repeat count after a delay).

If I hit CTRL then space and then quickly release, the space press and release never register.

Funny, the termux-x11 and xev output don't happen at the same time.  Instead of delaying, the space press immediately produces

```
07-21 08:21:59.692  6225  6225 D KeyEvent: We've got key event with FLAG_CANCELED, it will not be consumed. Details: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_CTRL_LEFT, scanCode=29, metaState=META_CTRL_ON|META_CTRL_LEFT_ON|META_NUM_LOCK_ON, flags=0x28, repeatCount=0, eventTime=3571212, downTime=3570287, deviceId=7, source=0x101, displayId=-1 }
07-21 08:22:00.092  6225  6225 D KeyEvent: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SPACE, scanCode=57, metaState=META_CTRL_ON|META_CTRL_LEFT_ON|META_NUM_LOCK_ON, flags=0x88, repeatCount=1, eventTime=3571611, downTime=3571210, deviceId=7, source=0x101, displayId=-1 }
07-21 08:22:00.092  6225  6225 D LorieNative: Sending key: 65 (57 62 1)
```

Note the 400 ms delay between the two.

I would imagine that these probably are not "fixable".  I guess the workaround is to hold space for at least 400ms longer when CTRL is pressed.

**Comment by twaik** [comment]
Probably. Anyway I do not see any way to overcome this behaviour. But at least now CTRL key is not cancelled too early.
Considering this as fixed.

**Comment by natebragg** [comment]
@twaik To clarify, the only "fix" I can imagine working is if there is some option in preferences to select this non-standard ctrl-space behavior, and then interpret KeyEvent of ACTION_UP for KEYCODE_CTRL_LEFT with META_CTRL_ON and FLAG_CANCELED as a space press.

**Comment by twaik** [comment]
I am not sure it is even an option. I am pretty much sure it will break other key combinations on other devices.

**Comment by natebragg** [comment]
I think that's how the termux-app does it.  And on other devices, the option would be default disabled.

**Comment by twaik** [comment]
No, it uses some other behaviour.

**Comment by twaik** [comment]
I can try it a bit later.

**Comment by twaik** [comment]
> I think that's how the termux-app does it

Termux-app uses different key handling model. And it is not compatible with termux-x11's one.

**Comment by natebragg** [comment]
Sadly no dice.  It had the same output as the `FLAG_CANCELLED` log above.  Well, thanks for pursuing this so diligantly.  You really tried to defeat it!  I'll have to live with the 400ms delay.  What a strange problem.

**Comment by twaik** [comment]
I was pretty sure it is not possible. In this build I am sending CTRL press in the case if there was CTRL release before event with META_CTRL_LEFT_ON or META_CTRL_RIGHT_ON.

**Comment by twaik** [comment]
So I am considering it as a firmware quirk.
