### ISSUE TITLE
startup problem with the current version c683eb3

### ISSUE THREAD

**Issue by RalfWerner** [termux/termux-x11#787]
In [discord](https://discord.com/channels/641256914684084234/955349025102630932/1329103421357424732) I had already described the problem, but got no answer, whether you **can repeat the script @twaik?**
```
[~]$ typeset -i i=0;x=termux-x11 WM=fluxbox y=com.termux.x11/.MainActivity px= X=app_;pkill $X
while [ -z "$px" -a $i -lt 3 ];do [ $i -eq 0 ]&& am start -n $y;$x :0 &
 sleep 1; px=`pgrep -o $X`;i+=1; $e Start$d:$x=$px try $i $d $X;
done ; echo Xserver and App started, Start Xclient $WM; $WM &
```
<details><summary> stdout with termux-info:</summary>

```
[2] 28023
[1]-  Terminated              $x $d > $tx/TX 2>&1
Start:0:termux-x11=28023 try 2 :0 app_
Xserver and App started, Start Xclient fluxbox
[3] 28030
Error: Couldn't connect to XServer:0
[~]$ termux-info
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+8651fd9
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~QpDj-E-FcZ3s_Ch0VVhlSw==/com.termux-OlWzngYwf4Zm9diGd7-H5Q==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=8840
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c3,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c3,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10259
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+f80b464
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+f80b464
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# sources.list.d/gcc.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
firefox/x11 134.0.1-1 aarch64 [upgradable from: 134.0]
git/stable 2.48.1 aarch64 [upgradable from: 2.48.0]
libsecret/stable 0.21.6 aarch64 [upgradable from: 0.21.4]
libsixel/stable 1.10.5 aarch64 [upgradable from: 1.10.3-2]
libsoup3/stable 3.6.3 aarch64 [upgradable from: 3.6.1]
libsqlite/stable 3.48.0 aarch64 [upgradable from: 3.47.2-1]
libuv/stable 1.50.0 aarch64 [upgradable from: 1.49.2]
termux-tools version:
1.44.6
Android version:
13
Kernel build information:
Linux localhost 4.14.113-27209537 #1 SMP PREEMPT Wed Oct 30 16:19:35 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-P610
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.widget versionCode:13
com.termux.x11 versionCode:15
com.termux.api versionCode:51
[3]+  Exit 1                  $WM
[~]$
```
</details>

It only occurs on the **first** start. After that, no more checks are made. Your suggestions to start and stop the XServer with a list of XClients is not an option for me, since my XClients are used spontaneously and also remotely and the XServer should only be stopped intentionally (e.g. reboot).

The error has occurred since version **a29a949**. Before that, everything worked fine and the Xserver could be used with `$px` pid. The value and process (`px= X=app_;pkill $X`) are only reset for the test above. `termux-info` takes **more than 1 second,** so `$WM` could be started afterwards.

**Comment by twaik** [comment]
1. I suggested you to use `termux-x11 :0 -xstartup "kill -USR1 $$; sleep infinite" to notify your script about X server being ready and use `trap '<some command>' SIGUSR1` to catch the signal. Using `sleep` maximum 3 times never was a reliable solution...
2. `pkill app_` is not a reliable command to kill X server. Readme suggests you to use `pkill -f com.termux.x11`.
3. I am failing to understand your script. It is not human readable. I had to use https://www.codeclean.net/tools/bash/ to understand what happens.
4. The fix that broke your script prevented creating second instance of X server which does nothing because it can not bind Unix domain socket and only wastes RAM and CPU time. It was upstream bug caused by updating one of dependencies which was reported to upstream and fixed by developers in master branch. I am not going to revert it.

**Comment by RalfWerner** [comment]
> I am failing to understand your script

I explained it in [discord](https://discord.com/channels/641256914684084234/955349025102630932/1329048429611061339) in simple words here again: `px` is the pid of the Xserver. If it is empty, the X11 app is started (once) and the XServer up to 3 times if something fails. Here it waits for 1 second before `px` is checked again and, if successful, the XClient fluxbox is started.
With `-f com.termux.x11` instead of `$X` the script does the same thing. **Didn't you notice that?**
> The fix that broke your script prevented creating second instance of X server

All I need is one XServer start and I have been working with this process for 6 years without any problems. If I use a second XServer then xvnc in parallel is off topic here. I don't understand why I should do signal checks. When the Xserver is started it runs for weeks without any problems and when it is stopped there is no more `px`. Additionally, neither RAM nor CPU is consumed, like any other Linux system that uses xstart when booting.

You still **haven't responded** if you were **able to execute** the script!

**Comment by twaik** [comment]
```
typeset -i i=0;x=termux-x11 WM=fluxbox y=com.termux.x11/.MainActivity px= X=app_;pkill $X
while [ -z "$px" -a $i -lt 3 ];do [ $i -eq 0 ]&& am start -n $y;$x :0 &
 sleep 1; px=`pgrep -o $X`;i+=1; $e Start$d:$x=$px try $i $d $X;
done ; echo Xserver and App started, Start Xclient $WM; $WM &
Starting: Intent { cmp=com.termux.x11/.MainActivity }
[1]+  Terminated              $x :0
[1] 24077
Start:termux-x11=24077: command not found
Xserver and App started, Start Xclient fluxbox
[2] 24106
~ $ Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.menuSearch
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.menuSearch
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.menuSearch
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to read: session.screen0.slit.acceptKdeDockapps
Setting default value
Failed to read: session.screen0.slit.autoHide
Setting default value
Failed to read: session.screen0.slit.maxOver
Setting default value
Failed to read: session.screen0.slit.placement
Setting default value
Failed to read: session.screen0.slit.alpha
Setting default value
Failed to read: session.screen0.slit.onhead
Setting default value
Failed to read: session.screen0.slit.layer
Setting default value
Failed to read: session.screen0.toolbar.autoHide
Setting default value
Failed to read: session.screen0.toolbar.maxOver
Setting default value
Failed to read: session.screen0.toolbar.visible
Setting default value
Failed to read: session.screen0.toolbar.widthPercent
Setting default value
Failed to read: session.screen0.toolbar.alpha
Setting default value
Failed to read: session.screen0.toolbar.layer
Setting default value
Failed to read: session.screen0.toolbar.onhead
Setting default value
Failed to read: session.screen0.toolbar.placement
Setting default value
Failed to read: session.screen0.toolbar.height
Setting default value
Failed to read: session.screen0.toolbar.tools
Setting default value
Failed to read: session.screen0.iconbar.mode
Setting default value
Failed to read: session.screen0.iconbar.alignment
Setting default value
Failed to read: session.screen0.iconbar.iconWidth
Setting default value
Failed to read: session.screen0.iconbar.iconTextPadding
Setting default value
Failed to read: session.screen0.iconbar.usePixmap
Setting default value
Failed to read: session.screen0.strftimeFormat
Setting default value
```
Fluxbox starts fine in my case...
As an option try to `sleep 3` after pkilling X server.

**Comment by RalfWerner** [comment]
> Fluxbox starts fine in my case...

That's interesting. I also suggested `sleep 2` successfully in [discord](https://discord.com/channels/641256914684084234/955349025102630932/1329093764052025436) as a solution. But that's just a _symptom correction_. I still don't understand why you have to wait **one** second after the XServer starts before an XClient starts.

**Thanks for testing!** Apparently the phenomenon isn't the same on all devices. I'll check a few others and then report the result. For you px=24077 and pw=`pgrep -o $WM`=24106 Instead of: `Error: Couldn't connect to XServer:0` 

As you can see in my stdout, this was achieved after `try 2` . But it is only displayed with `e=echo`. **Sorry**, I forgot it in my script!

**Comment by twaik** [comment]
> I still don't understand why you have to wait **one** second after the XServer starts before an XClient starts.

First of all app_process is a program which boots JVM into the process. JVM starts X server code after it boots. **BOTH JVM and X server have their own initialization sequences**. And, surprise surprise, they take some time. 

You are not ready to work right after awakening right? You need to prepare (brush your teeth, drink some coffee, exercise, get dressed, comb your hair), right? So why do you expect that from the program?

**Comment by RalfWerner** [comment]
> So why do you expect that from the program?

Because it has been doing that for the **last few years**. I already understood the *loader (JVM) processes. I'm not surprised, because it only worked on the second attempt `try 2`. That corresponds to the delay until it was ready.

To stay with your _Picture_, `px` was previously visible after I drove into my office, greeted my colleagues, started up the PC and all the tools, and put on the headset.
The analogy ends here, because I don't have to answer a call within a second and the caller doesn't get "no connection at this number".

I checked 2 more devices, one of which has **no problem** with sleep 1 and the other has **the same**. Both _problem devices_ are from Samsung. I will check 2 more. This will take a while because in addition to the current `apk` I also need `pkg up` and as a pensioner I am no longer the fastest.

**Comment by RalfWerner** [comment]
I checked my 5 devices. With `sleep 2` it is OK on all devices and with `sleep 1` the delay is sufficient for the 2 `armv7l` and not sufficient for `aarch64` architecture. If you are not prepared to get to the bottom of the phenomenon, I would change it on all devices and scripts (e.g part of  `bashrc`).

**Comment by RalfWerner** [comment]
Ok, I'm keen to learn and check out your suggestion: `termux-x11 :0 -xstartup "kill -USR1 $$; sleep infinite"`. This results in a syntax error for sleep, as I expected, because infinite is not a number, and ends the session. That doesn't work, so I use 3 instead. Then the session ends without syntax errors. So I write a script `twaik` with the following 3 lines:
```
e=echo X=app_ px=`pgrep $X`; $e start `date` px=$px;ps;# pkill $X
termux-x11 :0 -xstartup "kill -USR1 $$; sleep 3" # start script from twaik
$e Xserver started px=$px `date`;ps
```
I start this with `bash twaik` and get an error message, because my XServer+XClient was already started with [bashrc](https://github.com/termux/termux-x11/issues/787#issuecomment-2596048249) so I remove `#` in first line, do it again and the message from the last line is not displayed (`ps` manually) with stdout:
```
[~]$ bash twaik # without pkill
start Thu Jan 16 19:22:57 CET 2025 px=18853
  PID TTY          TIME CMD
16828 pts/2    00:00:00 /data/data/com.termux/files/usr/bin/bash
18853 pts/2    00:00:35 /system/bin/app_process
19836 pts/2    00:00:00 bash
19841 pts/2    00:00:00 openbox
22484 pts/2    00:00:00 bash
22487 pts/2    00:00:00 ps
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
Xserver started px=18853 Thu Jan 16 19:23:00 CET 2025
  PID TTY          TIME CMD
16828 pts/2    00:00:00 /data/data/com.termux/files/usr/bin/bash
18853 pts/2    00:00:35 /system/bin/app_process
19836 pts/2    00:00:00 bash
19841 pts/2    00:00:00 openbox
22484 pts/2    00:00:00 bash
22554 pts/2    00:00:00 ps

[~]$ bash twaik # with pkill
start Thu Jan 16 19:33:46 CET 2025 px=18853
  PID TTY          TIME CMD
16828 pts/2    00:00:00 /data/data/com.termux/files/usr/bin/bash
18853 pts/2    00:01:27 /system/bin/app_process
19836 pts/2    00:00:00 bash
19841 pts/2    00:00:00 openbox
28209 pts/2    00:00:00 bash
28212 pts/2    00:00:00 ps
User signal 1
[~]$ 28294 exited, status=0
[~]$ ps # check of processes
  PID TTY          TIME CMD
  882 pts/2    00:00:00 ps
16828 pts/2    00:00:00 /data/data/com.termux/files/usr/bin/bash
```
At the end, the Xserver and Xclient (`openbox` here) are killed. That can't be what you meant.

**Comment by twaik** [comment]
Seems like I mistyped. `sleep infinity`.
3 seconds timeout will make X server die after 3 secs. `xstartup` launches some command or script when X server is ready and waits for this process'es death to finish itself.

**Comment by RalfWerner** [comment]
> Seems like I mistyped. sleep infinity.

I corrected `infinity` [above](https://github.com/termux/termux-x11/issues/787#issuecomment-2596569725) with the same stdout. `date;twaik;date` also doesn't run forever but only for 2 seconds, like my script in the [first](https://github.com/termux/termux-x11/issues/787#issue-2792414481) commit but without XServer+Client. **Have you forgotten something else?**

**Comment by twaik** [comment]
Again. Do not use pgrep. Literally any process in the system can spawn new `sleep` instance and your check will give you false positive result.

You can use anonymous pipes, signals, unix/tcp/udp/abstract sockets (via netcat/nc), flag files.

Also why do not you want to try simple pinging X socket? Like `echo | socat UNIX-CONNECT:$TMPDIR/.X11-unix/X0 -; echo $?`.

**Comment by RalfWerner** [comment]
> Literally any process in the system can spawn new `sleep` instance

I wouldn't use `pgrep sleep` either. It was only used here so that I could open a session with XServer again after `bash twaik` (also just here to check). I call the concept OTS (One-Touch-Start), I have been using it for decades and have described it to you several times before. It is based on **pid control** (`$px,$pw ...`). If all processes for a task are active, nothing needs to be done.
> Like echo | socat UNIX-CONNECT:$TMPDIR/.X11-unix/X0 -; echo $?

As example: `[ -e u/bin/socat ]&& pkg in socat` is necessary pervious (but only in termux environment) to use  it. `$TMPDIR/.X11-unix/X0` is empty. Result of:`$e|socat UNIX-CONNECT:$TMPDIR/.X11-unix/X0 -;$e $?` is (`0`) even XServer (`px:  "22031 1 01:38:02 /system/bin/app_proces"`) **is running more than 90 minutes.**

**Comment by twaik** [comment]
>  is empty.

It is not empty. It is a unix domain socket, it does not contain data...

> Result of ... is (0) even XServer ... is running more than 90 minutes.

0 is success, 1 for error + socat will print error to stdout... You did not try it without X server running, did you?

**Comment by RalfWerner** [comment]
> You did not try it without X server running, did you?

Thanks for the _socket_ explanation. I added to _my_ script [above](https://github.com/termux/termux-x11/issues/787#issuecomment-2595329412), used your _socket check_ (`twaik`) to _reset_ `px` and start it with `. twaik` (in Session):
```
# Environment from Termux Session with bashrc and kill XServer
typeset -i i=0;e=echo tx=$TMPDIR x=termux-x11 WM=fluxbox y=com.termux.x11/.MainActivity px= X=app_;pkill $X

# Loop to start XServer (px) and Window Manager in background (>$tx/X 2>& for no log in stdout)
while [ -z "$px" -a $i -lt 3 ];do [ $i -eq 0 ]&& am start -n $y; $x :0>$tx/X 2>&1&
 sleep 1;twaik=`$e|socat UNIX-CONNECT:$tx/.X11-unix/X0 -;$e $?`
 px=`pgrep -o $X`;i+=1;$e Start:$x=$px try $i $X twaik=$twaik;[ $twaik == 1 ]&&px=
done ; echo Xserver and App started, Start Xclient $WM; $WM &
```
That works, but needs an additional loop (second) related to `sleep 2`, because it also takes time. However, `twaik` does not replace the pid `px`. I also tried replacing `$y;` with `$y &&`, which means `$x` only starts once. But that didn't work, possibly because `$y` wasn't finished yet. Then moving `sleep 1` behind `$y;` should have helped, but that doesn't work either.

If `$X=Xwayland`, it works too. But it doesn't need to, because the problem with these issues **never occurred before**. I sometimes use a _toggle_ to version 01.02.04 (Dec 21 2022) because _simple gestures_ with `Emulate mouse` were still possible and not all packages are compatible with `Direct mode`, which is what I currently use mostly. If you implement _this_ again in actual version, there is hardly any reason to use the 3 year old version.

I will change all my scripts accordingly. **Thanks!**

**Comment by twaik** [comment]
And here we start again. I am not going to add it back. Old handler was removed because it had serious bugs and replaced by chromoting implementation. I do not want to get back to this conversation again. And I asked you to not start it again multiple times.

**Comment by RalfWerner** [comment]
> durch eine Chromoting-Implementierung ersetzt.

I don't really understand the argument. I work a lot with Chrome and Remote Desktop and have never discovered the _"ignore simple gestures"_ effect there - but it's OK for my XClients. There is also the `Direct mode`, which doesn't have this bug and which I just mainly use.

The [Video](https://github.com/user-attachments/assets/7464d615-9244-4096-a53a-9472fd64fc79) (how should it be) doesn't handle the `touchMode`, but rather some missing and covered elements. If the same 12 seconds are done with the current X11 version, this is easy to see. I have also dealt with this in [other](https://github.com/termux/termux-x11/issues/678#issuecomment-2504547290) issues and with the `*_HELPER` feature it has become more serious, so it doesn't need to be solved here.
